name: CI/CD
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of the env"
        required: true
      actions:
        description: "Action to be performed"
        type: choice
        options:
          - "Create"
          - "Destroy"

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:

  parse-inputs:
    name: "Parse user inputs"
    runs-on: ubuntu-latest
    outputs:
      ccb_env: ${{ steps.parse.outputs.ccb_env }}
    steps:
      - name: Parse input values
        id: parse
        run: |
          echo "ccb_env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

  create-new-env:
    name: "Create environment structure"
    runs-on: ubuntu-latest
    needs: [ parse-inputs ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create new directory sturcture
        id: new_env
        run: |
          pwd
          ls -latrh

      - name: Copy the dir structure
        run: |
          cp -fR ./modules/ ./${{ needs.parse-inputs.outputs.ccb_env }}
          cd ${{ needs.parse-inputs.outputs.ccb_env }}
          pwd
          ls -latrh