name: Input Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter a string value'
        required: true
      flag:
        description: 'Enter a boolean value (true/false)'
        required: true

jobs:
  process_input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "INPUT_NAME=${{ github.event.inputs.name }}" >> $GITHUB_ENV
          echo "INPUT_FLAG=${{ github.event.inputs.flag }}" >> $GITHUB_ENV

      - name: Display inputs
        run: |
          echo "String: $INPUT_NAME"
          echo "Boolean: $INPUT_FLAG"
