name: CI/CD
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of the env"
        required: true
      app_ami:
        description: "App AMI"
        required: true
      db_ami:
        description: "DB AMI"
        required: true


permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:

  parse-inputs:
    name: "Parse user inputs"
    runs-on: ubuntu-latest
    outputs:
      ccb_env: ${{ steps.parse.outputs.ccb_env }}
      app_ami: ${{ steps.parse.outputs.app_ami }}
      db_ami: ${{ steps.parse.outputs.db_ami }}
    steps:
      - name: Parse input values
        id: parse
        run: |
          echo "ccb_env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          echo "app_ami=${{ github.event.inputs.app_ami }}" >> $GITHUB_OUTPUT
          echo "db_ami=${{ github.event.inputs.db_ami }}" >> $GITHUB_OUTPUT

  create-new-env:
    name: "Create environment structure"
    runs-on: ubuntu-latest
    needs: [ parse-inputs ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create new directory sturcture
        id: new_env
        run: |
          pwd
          ls -latrh

      - name: Create a branch
        id: branch
        run: |
          branch_name="${{ github.event.inputs.environment }}-$(date +'%Y%m%d%H%m%S')"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          git checkout -b $branch_name


      - name: Copy the dir structure
        run: |
          git branch
          cp -fR envtemplate/ ./${{ needs.parse-inputs.outputs.ccb_env }}/
          cd ${{ needs.parse-inputs.outputs.ccb_env }}
          pwd
          ls -latrh
          app_ami=${{ needs.parse-inputs.outputs.app_ami }}
          db_ami=${{ needs.parse-inputs.outputs.db_ami }}

          jq '.app.app_ami=$app_ami | .app.db_ami=$db_ami  | .network.vpc_id="net"' config.json > config_updated.json && mv config_updated.json config.json
          cat config.json

      - name: Git commit and push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          whoami
          gh auth status
          git status
          git add ${{ needs.parse-inputs.outputs.ccb_env }}/
          git commit -m "Adding the new env: ${{ needs.parse-inputs.outputs.ccb_env }}"
          git push origin ${{ steps.branch.branch_name }}