name: CI/CD
on:
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of the role to create"
        required: true

env:
  tf_version: '1.5.2'
  working-directory: '${{ github.repository }}/modules'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE }}
          aws-region: ap-southeast-2


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.2"  # Adjust the version as needed

      - name: Terraform init
        working-directory: '${{ github.repository }}/modules/'
        run: terraform init

      - name: Terraform plan
        working-directory: '${{ github.repository }}/modules/'
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}" -out=tfplan

      - name: Terraform apply
        working-directory: '${{ github.repository }}/modules/'
        run: terraform apply -auto-approve tfplan
