name: CI/CD
on:
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of the role to create"
        required: true
        default: "dummy-test"

env:
  tf_version: '1.5.2'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.2"  # Adjust the version as needed

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}" -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
