run-name: Plan on `${{ inputs.deployment_environment }}` by @${{ github.actor }}
on:
  workflow_call:
    deployment_environment:
      description: "Deployment Environment"
      type: string
      required: true


jobs:
  setup-env:
    name: "0> Setup Environment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}

      - name: "Hello Hello"
        run: |
          echo "Hi there.. Cleaning up now !!!!"